server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modulo_ventas
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
