server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modulo_ventas
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  sql:
    init:
      mode: always

  jackson:
    serialization:
      write-dates-as-timestamps: false
        # App Properties
sponce:
    app:
      jwtSecret: ======================sponce=Spring===========================
      jwtExpirationMs: 86400000